#!/usr/bin/env python
"""Standalone script to test the reasoning_parser + speculative_decoding + structured_output fix."""

from unittest.mock import Mock

from vllm.config import ModelConfig, SchedulerConfig, VllmConfig
from vllm.reasoning import ReasoningParser
from vllm.v1.request import Request
from vllm.v1.structured_output import StructuredOutputManager


def test_spec_token_validation_during_reasoning_transition():
    """
    Test that speculative tokens generated during reasoning are validated
    when reasoning transitions from not-ended to ended.

    This tests the bug where tokens generated by speculative decoding
    during reasoning phase are returned as content without being validated
    against the grammar.
    """
    print("Testing reasoning parser + speculative decoding + structured output interaction...")

    # Setup mock VLLM config with speculative decoding enabled
    config = Mock(spec=VllmConfig)
    config.model_config = Mock(spec=ModelConfig)
    config.model_config.skip_tokenizer_init = True
    config.model_config.get_vocab_size = Mock(return_value=50000)
    config.model_config.runner_type = "generate"
    config.model_config.tokenizer = "test-tokenizer"
    config.model_config.tokenizer_mode = "auto"
    config.model_config.trust_remote_code = False
    config.model_config.tokenizer_revision = None

    config.scheduler_config = Mock(spec=SchedulerConfig)
    config.scheduler_config.max_num_seqs = 128

    config.structured_outputs_config = Mock()
    config.structured_outputs_config.reasoning_parser = "test_parser"
    config.structured_outputs_config.enable_in_reasoning = False
    config.structured_outputs_config.reasoning_parser_plugin = None

    config.speculative_config = Mock()
    config.speculative_config.num_speculative_tokens = 3

    config.parallel_config = Mock()
    config.parallel_config.distributed_executor_backend = None

    # Setup mock request with structured output and reasoning
    request = Mock(spec=Request)
    request.structured_output_request = Mock()
    request.structured_output_request.reasoning_ended = False
    request.structured_output_request.grammar = Mock()
    request.structured_output_request.grammar.is_terminated = Mock(
        return_value=False
    )
    request.structured_output_request.grammar.accept_tokens = Mock(
        return_value=True
    )
    request.structured_output_request.grammar.validate_tokens = Mock(
        side_effect=lambda x: x
    )
    request.structured_output_request.grammar.rollback = Mock()
    request.use_structured_output = True
    request.prompt_token_ids = [1, 2, 3, 4, 5]
    request.all_token_ids = [1, 2, 3, 4, 5, 6, 7, 8]
    request.num_computed_tokens = 5
    request.num_output_placeholders = 0
    request.spec_token_ids = [100, 101, 102]
    request.request_id = "test_req"
    request.is_prefill_chunk = False
    request.is_finished = Mock(return_value=False)

    # Setup mock reasoning parser that ends at token 8
    parser = Mock(spec=ReasoningParser)
    parser.is_reasoning_end_streaming = Mock(side_effect=lambda all_ids, delta_ids: len(all_ids) >= 8)

    manager = StructuredOutputManager(config)
    manager.reasoner = parser

    # Initially, reasoning has not ended
    assert manager.should_fill_bitmask(request) is False, "should_fill_bitmask should be False when reasoning has not ended"
    assert manager.should_advance(request) is False, "should_advance should be False when reasoning has not ended"
    print("✓ Initial state: reasoning not ended")

    # Simulate spec tokens generated during reasoning
    # These should NOT be validated yet
    spec_tokens_during_reasoning = [100, 101, 102]
    request.spec_token_ids = spec_tokens_during_reasoning

    # Validate should return False (don't advance grammar)
    should_advance = manager.should_advance(request)
    assert should_advance is False, "should_advance should still be False"
    print("✓ Spec tokens during reasoning: not validated")

    # Simulate the reasoning ending transition
    # Add more tokens to trigger reasoning end
    request.all_token_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    request.num_computed_tokens = 9

    # Now reasoning should end
    should_advance_after = manager.should_advance(request)
    assert should_advance_after is False, "should_advance should be False in the step reasoning ends"
    assert request.structured_output_request.reasoning_ended is True, "reasoning_ended should be True"
    print("✓ Reasoning transitioned to ended state")

    # After reasoning ends, should_fill_bitmask should return True
    assert manager.should_fill_bitmask(request) is True, "should_fill_bitmask should be True after reasoning ends"
    print("✓ Grammar is now active (bitmask filling enabled)")

    # And now spec tokens should be validated
    should_advance_next = manager.should_advance(request)
    assert should_advance_next is True, "should_advance should be True in next step after reasoning ends"
    print("✓ Grammar advancement is now enabled")

    # The spec tokens from during reasoning should still need to be validated
    # This is the failing case - these tokens weren't validated
    validated_tokens = request.structured_output_request.grammar.validate_tokens(
        request.spec_token_ids
    )
    assert validated_tokens == spec_tokens_during_reasoning, "Spec tokens should be validated"
    print("✓ Spec tokens are validated against grammar")

    # Now test the fix: simulate update_draft_token_ids logic
    print("\n--- Testing update_draft_token_ids logic ---")

    # Reset the request to simulate reasoning ending during draft token update
    request.structured_output_request.reasoning_ended = False
    request.all_token_ids = [1, 2, 3, 4, 5, 6, 7]  # Still in reasoning
    request.spec_token_ids = [100, 101, 102]

    # Store reasoning state before update
    reasoning_ended_before = request.structured_output_request.reasoning_ended

    # Simulate tokens being generated and reasoning ending
    request.all_token_ids = [1, 2, 3, 4, 5, 6, 7, 8]  # Reasoning ends
    should_advance = manager.should_advance(request)
    reasoning_ended_after = request.structured_output_request.reasoning_ended

    print(f"  Reasoning before: {reasoning_ended_before}")
    print(f"  Reasoning after: {reasoning_ended_after}")

    # The KEY fix: if reasoning transitioned from not-ended to ended,
    # discard speculative tokens
    if reasoning_ended_before is False and reasoning_ended_after:
        print("  ⚠ Reasoning just ended - discarding spec tokens!")
        spec_token_ids = []
    elif should_advance:
        print("  ✓ Advancing grammar and validating spec tokens")
        spec_token_ids = request.structured_output_request.grammar.validate_tokens(request.spec_token_ids)
    else:
        print("  Still in reasoning mode")
        spec_token_ids = request.spec_token_ids

    assert reasoning_ended_before is False, "Reasoning should not have ended before"
    assert reasoning_ended_after is True, "Reasoning should have ended"
    assert spec_token_ids == [], "Spec tokens should be discarded during reasoning transition"
    print("✓ Spec tokens correctly discarded during reasoning transition")

    print("\n✅ All tests passed!")
    return True


if __name__ == "__main__":
    try:
        test_spec_token_validation_during_reasoning_transition()
        print("\n🎉 Fix validated successfully!")
    except AssertionError as e:
        print(f"\n❌ Test failed: {e}")
        import traceback
        traceback.print_exc()
        exit(1)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        exit(1)