# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

"""Test for speculative decoding + reasoning parser + structured output interaction."""

from unittest.mock import Mock

import pytest

from vllm.config import ModelConfig, SchedulerConfig, VllmConfig
from vllm.reasoning import ReasoningParser
from vllm.v1.request import Request
from vllm.v1.structured_output import StructuredOutputManager


class TestSpecDecodeReasoningStructuredOutput:
    """Test the interaction between speculative decoding and structured output
    with reasoning parser enabled.
    """

    @pytest.fixture
    def mock_vllm_config(self):
        """Create a mock VllmConfig with speculative decoding enabled."""
        config = Mock(spec=VllmConfig)
        config.model_config = Mock(spec=ModelConfig)
        config.model_config.skip_tokenizer_init = True
        config.model_config.get_vocab_size = Mock(return_value=50000)
        config.model_config.runner_type = "generate"
        config.model_config.tokenizer = "test-tokenizer"
        config.model_config.tokenizer_mode = "auto"
        config.model_config.trust_remote_code = False
        config.model_config.tokenizer_revision = None

        config.scheduler_config = Mock(spec=SchedulerConfig)
        config.scheduler_config.max_num_seqs = 128

        config.structured_outputs_config = Mock()
        config.structured_outputs_config.reasoning_parser = "test_parser"
        config.structured_outputs_config.enable_in_reasoning = False
        config.structured_outputs_config.reasoning_parser_plugin = None

        config.speculative_config = Mock()
        config.speculative_config.num_speculative_tokens = 3

        config.parallel_config = Mock()
        config.parallel_config.distributed_executor_backend = None

        return config

    @pytest.fixture
    def mock_request(self):
        """Create a mock request with structured output and reasoning."""
        request = Mock(spec=Request)
        request.structured_output_request = Mock()
        request.structured_output_request.reasoning_ended = False
        request.structured_output_request.grammar = Mock()
        request.structured_output_request.grammar.is_terminated = Mock(
            return_value=False
        )
        request.structured_output_request.grammar.accept_tokens = Mock(
            return_value=True
        )
        request.structured_output_request.grammar.validate_tokens = Mock(
            side_effect=lambda x: x
        )
        request.structured_output_request.grammar.rollback = Mock()
        request.use_structured_output = True
        request.prompt_token_ids = [1, 2, 3, 4, 5]
        request.all_token_ids = [1, 2, 3, 4, 5, 6, 7, 8]
        request.num_computed_tokens = 5
        request.num_output_placeholders = 0
        request.spec_token_ids = [100, 101, 102]
        request.request_id = "test_req"
        request.is_prefill_chunk = False
        request.is_finished = Mock(return_value=False)
        return request

    @pytest.fixture
    def mock_reasoner(self):
        """Create a mock reasoning parser that ends at token 8."""
        parser = Mock(spec=ReasoningParser)
        parser.is_reasoning_end_streaming = Mock(side_effect=lambda all_ids, delta_ids: len(all_ids) >= 8)
        return parser

    def test_spec_token_validation_during_reasoning_transition(
        self, mock_vllm_config, mock_request, mock_reasoner
    ):
        """
        Test that speculative tokens generated during reasoning are validated
        when reasoning transitions from not-ended to ended.

        This tests the bug where tokens generated by speculative decoding
        during reasoning phase are returned as content without being validated
        against the grammar.
        """
        manager = StructuredOutputManager(mock_vllm_config)
        manager.reasoner = mock_reasoner

        # Initially, reasoning has not ended
        assert manager.should_fill_bitmask(mock_request) is False
        assert manager.should_advance(mock_request) is False

        # Simulate spec tokens generated during reasoning
        # These should NOT be validated yet
        spec_tokens_during_reasoning = [100, 101, 102]
        mock_request.spec_token_ids = spec_tokens_during_reasoning

        # Validate should return False (don't advance grammar)
        should_advance = manager.should_advance(mock_request)
        assert should_advance is False

        # Simulate the reasoning ending transition
        # Add more tokens to trigger reasoning end
        mock_request.all_token_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9]
        mock_request.num_computed_tokens = 9

        # Now reasoning should end
        should_advance_after = manager.should_advance(mock_request)
        assert should_advance_after is False
        assert mock_request.structured_output_request.reasoning_ended is True

        # After reasoning ends, should_fill_bitmask should return True
        assert manager.should_fill_bitmask(mock_request) is True

        # And now spec tokens should be validated
        assert manager.should_advance(mock_request) is True

        # The spec tokens from during reasoning should still need to be validated
        # This is the failing case - these tokens weren't validated
        validated_tokens = mock_request.structured_output_request.grammar.validate_tokens(
            mock_request.spec_token_ids
        )
        assert validated_tokens == spec_tokens_during_reasoning
        mock_request.structured_output_request.grammar.validate_tokens.assert_called_once()